"""Add retry count to connector runs

Revision ID: 404d826f1457
Revises: 5df083563c4e
Create Date: 2026-07-22 16:51:43.627831

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404d826f1457'
down_revision: Union[str, None] = '5df083563c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector_runs', sa.Column('retry_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connector_runs', 'retry_count')
    # ### end Alembic commands ###
