"""Add metrics tables

Revision ID: 56e7e84ceb13
Revises: 404d826f1457
Create Date: 2026-07-22 17:03:50.541103

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56e7e84ceb13'
down_revision: Union[str, None] = '404d826f1457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('connector_run_id', sa.BigInteger(), nullable=False),
    sa.Column('integration_id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_run_id'], ['connector_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_metrics_connector_run_id'), 'raw_metrics', ['connector_run_id'], unique=False)
    op.create_index(op.f('ix_raw_metrics_id'), 'raw_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_raw_metrics_integration_id'), 'raw_metrics', ['integration_id'], unique=False)
    op.create_index(op.f('ix_raw_metrics_project_id'), 'raw_metrics', ['project_id'], unique=False)
    op.create_table('normalized_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('location_id', sa.BigInteger(), nullable=True),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('raw_metric_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_metric_id'], ['raw_metrics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'metric_type', 'metric_date', 'source_provider', name='uix_normalized_metrics_upsert')
    )
    op.create_index(op.f('ix_normalized_metrics_id'), 'normalized_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_normalized_metrics_location_id'), 'normalized_metrics', ['location_id'], unique=False)
    op.create_index(op.f('ix_normalized_metrics_metric_date'), 'normalized_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_normalized_metrics_metric_type'), 'normalized_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_normalized_metrics_project_id'), 'normalized_metrics', ['project_id'], unique=False)
    op.create_index(op.f('ix_normalized_metrics_raw_metric_id'), 'normalized_metrics', ['raw_metric_id'], unique=False)
    op.alter_column('integrations', 'provider',
               existing_type=mysql.ENUM('PROCORE', 'AUTODESK', 'GENERIC_WEBHOOK'),
               type_=sa.Enum('PROCORE', 'AUTODESK', 'GENERIC_WEBHOOK', 'GOOGLE_ANALYTICS', 'GOOGLE_SEARCH_CONSOLE', 'META', 'AHREFS', 'SEMRUSH', name='integrationprovider'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('integrations', 'provider',
               existing_type=sa.Enum('PROCORE', 'AUTODESK', 'GENERIC_WEBHOOK', 'GOOGLE_ANALYTICS', 'GOOGLE_SEARCH_CONSOLE', 'META', 'AHREFS', 'SEMRUSH', name='integrationprovider'),
               type_=mysql.ENUM('PROCORE', 'AUTODESK', 'GENERIC_WEBHOOK'),
               existing_nullable=False)
    op.drop_index(op.f('ix_normalized_metrics_raw_metric_id'), table_name='normalized_metrics')
    op.drop_index(op.f('ix_normalized_metrics_project_id'), table_name='normalized_metrics')
    op.drop_index(op.f('ix_normalized_metrics_metric_type'), table_name='normalized_metrics')
    op.drop_index(op.f('ix_normalized_metrics_metric_date'), table_name='normalized_metrics')
    op.drop_index(op.f('ix_normalized_metrics_location_id'), table_name='normalized_metrics')
    op.drop_index(op.f('ix_normalized_metrics_id'), table_name='normalized_metrics')
    op.drop_table('normalized_metrics')
    op.drop_index(op.f('ix_raw_metrics_project_id'), table_name='raw_metrics')
    op.drop_index(op.f('ix_raw_metrics_integration_id'), table_name='raw_metrics')
    op.drop_index(op.f('ix_raw_metrics_id'), table_name='raw_metrics')
    op.drop_index(op.f('ix_raw_metrics_connector_run_id'), table_name='raw_metrics')
    op.drop_table('raw_metrics')
    # ### end Alembic commands ###
