"""Add dashboard summary table

Revision ID: e856abf36aa6
Revises: 56e7e84ceb13
Create Date: 2026-07-22 17:12:52.572231

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e856abf36aa6'
down_revision: Union[str, None] = '56e7e84ceb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_summaries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('kpi_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('aggregated_value', sa.JSON(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'kpi_type', 'period_start', 'period_end', name='uix_dashboard_summary')
    )
    op.create_index(op.f('ix_dashboard_summaries_id'), 'dashboard_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_dashboard_summaries_kpi_type'), 'dashboard_summaries', ['kpi_type'], unique=False)
    op.create_index(op.f('ix_dashboard_summaries_period_end'), 'dashboard_summaries', ['period_end'], unique=False)
    op.create_index(op.f('ix_dashboard_summaries_period_start'), 'dashboard_summaries', ['period_start'], unique=False)
    op.create_index(op.f('ix_dashboard_summaries_project_id'), 'dashboard_summaries', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dashboard_summaries_project_id'), table_name='dashboard_summaries')
    op.drop_index(op.f('ix_dashboard_summaries_period_start'), table_name='dashboard_summaries')
    op.drop_index(op.f('ix_dashboard_summaries_period_end'), table_name='dashboard_summaries')
    op.drop_index(op.f('ix_dashboard_summaries_kpi_type'), table_name='dashboard_summaries')
    op.drop_index(op.f('ix_dashboard_summaries_id'), table_name='dashboard_summaries')
    op.drop_table('dashboard_summaries')
    # ### end Alembic commands ###
