"""Add integrations table

Revision ID: 3975335fbed2
Revises: 0004
Create Date: 2026-07-22 16:33:32.379725

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3975335fbed2'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.Enum('PROCORE', 'AUTODESK', 'GENERIC_WEBHOOK', name='integrationprovider'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONNECTED', 'ERROR', 'DISABLED', name='integrationstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations_client_id'), 'integrations', ['client_id'], unique=False)
    op.create_index('ix_integrations_client_id_provider', 'integrations', ['client_id', 'provider'], unique=False)
    op.create_index('ix_integrations_deleted_at', 'integrations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_provider'), 'integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_integrations_status'), 'integrations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrations_status'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_provider'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_index('ix_integrations_deleted_at', table_name='integrations')
    op.drop_index('ix_integrations_client_id_provider', table_name='integrations')
    op.drop_index(op.f('ix_integrations_client_id'), table_name='integrations')
    op.drop_table('integrations')
    # ### end Alembic commands ###
