"""Add connector runs table

Revision ID: 5df083563c4e
Revises: 3975335fbed2
Create Date: 2026-07-22 16:41:13.727826

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5df083563c4e'
down_revision: Union[str, None] = '3975335fbed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('integration_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', name='runstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['integration_id'], ['integrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_connector_runs_deleted_at', 'connector_runs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_connector_runs_id'), 'connector_runs', ['id'], unique=False)
    op.create_index(op.f('ix_connector_runs_integration_id'), 'connector_runs', ['integration_id'], unique=False)
    op.create_index(op.f('ix_connector_runs_status'), 'connector_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_connector_runs_status'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_integration_id'), table_name='connector_runs')
    op.drop_index(op.f('ix_connector_runs_id'), table_name='connector_runs')
    op.drop_index('ix_connector_runs_deleted_at', table_name='connector_runs')
    op.drop_table('connector_runs')
    # ### end Alembic commands ###
