"""Add integrations table

Revision ID: a4b83881dcf3
Revises: 0004
Create Date: 2026-07-22 16:28:51.127599

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b83881dcf3'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('locations_ibfk_1'), 'locations', type_='foreignkey')
    op.drop_constraint(op.f('locations_ibfk_2'), 'locations', type_='foreignkey')
    op.create_foreign_key(None, 'locations', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'locations', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('projects_ibfk_1'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_ibfk_1'), 'projects', 'clients', ['client_id'], ['id'])
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.create_foreign_key(op.f('locations_ibfk_2'), 'locations', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('locations_ibfk_1'), 'locations', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###
